-- migrations/0001_initial.sql
-- frank-blog-cms D1 schema — Phase 1
-- Per ADR-001 ~ ADR-010 + D-1 ~ D-6 + docs/PHASE-0-ANALYSIS.md
--
-- Apply with:
--   wrangler d1 migrations apply frank-blog-db --local
--   wrangler d1 migrations apply frank-blog-db --remote
-- (wrangler auto-tracks applied migrations in d1_migrations table)
--
-- Conventions:
--   - Timestamps: TEXT (ISO 8601 UTC via datetime('now'))
--   - Booleans:   INTEGER (0/1) with CHECK
--   - Enums:      TEXT with CHECK constraints
--   - IDs:        INTEGER PRIMARY KEY AUTOINCREMENT
--   - Foreign keys: D1 enforces by default (PRAGMA foreign_keys = ON)

-- ============================================================
-- 1. users (ADR-004 / D-4)
-- ============================================================
-- role: 'admin' (MVP UI) | 'editor' (v1.1 schema only, no UI)
-- password_hash: PBKDF2-SHA256 format
--   pbkdf2_sha256$<iterations>$<salt_b64>$<hash_b64>
--   generated by scripts/seed-admin.mjs
CREATE TABLE users (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  username        TEXT    UNIQUE NOT NULL,
  email           TEXT    UNIQUE NOT NULL,
  password_hash   TEXT    NOT NULL,
  display_name    TEXT,
  role            TEXT    NOT NULL DEFAULT 'admin'
                          CHECK (role IN ('admin', 'editor')),
  status          TEXT    NOT NULL DEFAULT 'active'
                          CHECK (status IN ('active', 'disabled')),
  created_at      TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at      TEXT    NOT NULL DEFAULT (datetime('now')),
  last_login_at   TEXT
);

CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email    ON users(email);

-- ============================================================
-- 2. sessions (HttpOnly Cookie sessions — ADR-002 / D-4)
-- ============================================================
-- token_hash: SHA-256 hex of session token (NEVER store plaintext token)
-- expires_at: ISO timestamp; cleanup jobs delete expired rows
CREATE TABLE sessions (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id         INTEGER NOT NULL,
  token_hash      TEXT    UNIQUE NOT NULL,
  expires_at      TEXT    NOT NULL,
  created_at      TEXT    NOT NULL DEFAULT (datetime('now')),
  last_used_at    TEXT    NOT NULL DEFAULT (datetime('now')),
  ip_hash         TEXT,
  user_agent      TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_sessions_token_hash ON sessions(token_hash);
CREATE INDEX idx_sessions_expires_at ON sessions(expires_at);
CREATE INDEX idx_sessions_user_id    ON sessions(user_id);

-- ============================================================
-- 3. posts (ADR-005 / D-6 — MDX source + frontmatter preserved)
-- ============================================================
-- Implicit translation group: same slug across 3 locales = 3 rows
-- UNIQUE (collection, locale, slug) guarantees idempotent imports
--
-- content column = FULL MDX file (frontmatter + body), byte-level SoT
-- description_raw = original YAML literal (block scalar preserved verbatim)
-- description_text = parsed plain string (for queries / SEO meta)
CREATE TABLE posts (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  collection       TEXT    NOT NULL DEFAULT 'posts'
                           CHECK (collection IN ('posts', 'notes')),
  locale           TEXT    NOT NULL
                           CHECK (locale IN ('zh', 'ja', 'en')),
  slug             TEXT    NOT NULL,
  title            TEXT    NOT NULL,
  description_raw  TEXT    NOT NULL,           -- D-6 raw YAML (block scalar)
  description_text TEXT    NOT NULL,           -- parsed plain text
  content          TEXT    NOT NULL,           -- D-6 full MDX file
  content_format   TEXT    NOT NULL DEFAULT 'mdx'
                           CHECK (content_format IN ('mdx', 'md')),
  excerpt          TEXT,
  cover_image      TEXT,
  status           TEXT    NOT NULL DEFAULT 'draft'
                           CHECK (status IN ('draft', 'published', 'archived')),
  published_at     TEXT,
  created_at       TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at       TEXT    NOT NULL DEFAULT (datetime('now')),
  author_id        INTEGER,
  reading_time     TEXT,
  view_count       INTEGER NOT NULL DEFAULT 0,
  is_featured      INTEGER NOT NULL DEFAULT 0
                           CHECK (is_featured IN (0, 1)),
  tags             TEXT,                        -- MVP: JSON array string
  FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE (collection, locale, slug)
);

CREATE INDEX idx_posts_slug           ON posts(slug);
CREATE INDEX idx_posts_locale         ON posts(locale);
CREATE INDEX idx_posts_status         ON posts(status);
CREATE INDEX idx_posts_published_at   ON posts(published_at);
CREATE INDEX idx_posts_collection     ON posts(collection);
CREATE INDEX idx_posts_locale_status  ON posts(locale, status);
CREATE INDEX idx_posts_feat_status    ON posts(is_featured, status);

-- ============================================================
-- 4. post_revisions (schema reserved — v1.1 writes history)
-- ============================================================
CREATE TABLE post_revisions (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  post_id         INTEGER NOT NULL,
  title           TEXT    NOT NULL,
  content         TEXT    NOT NULL,           -- full MDX snapshot
  excerpt         TEXT,
  description_raw TEXT,
  created_by      INTEGER,
  created_at      TEXT    NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (post_id)    REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_post_revisions_post_id    ON post_revisions(post_id);
CREATE INDEX idx_post_revisions_created_at ON post_revisions(created_at);

-- ============================================================
-- 5. categories (ADR-006 — v1.1, schema reserved)
-- ============================================================
CREATE TABLE categories (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  name        TEXT    UNIQUE NOT NULL,
  slug        TEXT    UNIQUE NOT NULL,
  description TEXT,
  created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at  TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_categories_slug ON categories(slug);

-- ============================================================
-- 6. tags (ADR-006 — v1.1, schema reserved)
-- ============================================================
CREATE TABLE tags (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  name       TEXT    UNIQUE NOT NULL,
  slug       TEXT    UNIQUE NOT NULL,
  created_at TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_tags_slug ON tags(slug);

-- ============================================================
-- 7. post_categories (ADR-006 — v1.1, schema reserved)
-- ============================================================
CREATE TABLE post_categories (
  post_id     INTEGER NOT NULL,
  category_id INTEGER NOT NULL,
  PRIMARY KEY (post_id, category_id),
  FOREIGN KEY (post_id)     REFERENCES posts(id)       ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

CREATE INDEX idx_post_categories_post_id     ON post_categories(post_id);
CREATE INDEX idx_post_categories_category_id ON post_categories(category_id);

-- ============================================================
-- 8. post_tags (ADR-006 — v1.1, schema reserved; MVP uses posts.tags JSON)
-- ============================================================
CREATE TABLE post_tags (
  post_id INTEGER NOT NULL,
  tag_id  INTEGER NOT NULL,
  PRIMARY KEY (post_id, tag_id),
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id)  REFERENCES tags(id)  ON DELETE CASCADE
);

CREATE INDEX idx_post_tags_post_id ON post_tags(post_id);
CREATE INDEX idx_post_tags_tag_id  ON post_tags(tag_id);

-- ============================================================
-- 9. media (ADR-006 — v1.1; schema reserved; binary stays in R2)
-- ============================================================
CREATE TABLE media (
  id                INTEGER PRIMARY KEY AUTOINCREMENT,
  filename          TEXT    UNIQUE NOT NULL,
  original_filename TEXT    NOT NULL,
  mime_type         TEXT    NOT NULL,
  size              INTEGER NOT NULL,
  url               TEXT    NOT NULL,         -- R2 URL or local path
  alt               TEXT,
  width             INTEGER,
  height            INTEGER,
  created_at        TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at        TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_media_filename ON media(filename);

-- ============================================================
-- 10. settings (key-value site config)
-- ============================================================
CREATE TABLE settings (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ============================================================
-- 11. admin_logs (audit log — MVP doesn't write; schema reserved)
-- ============================================================
CREATE TABLE admin_logs (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id       INTEGER,
  action        TEXT NOT NULL,                -- login / logout / create_post / update_post / publish_post / delete_post / etc.
  resource_type TEXT,                         -- 'post' / 'media' / 'user' / ...
  resource_id   INTEGER,
  ip_hash       TEXT,
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_admin_logs_user_id    ON admin_logs(user_id);
CREATE INDEX idx_admin_logs_created_at ON admin_logs(created_at);
CREATE INDEX idx_admin_logs_action     ON admin_logs(action);

-- ============================================================
-- Seed data: site settings defaults
-- ============================================================
INSERT INTO settings (key, value) VALUES
  ('site_title',        'Frank Ding'),
  ('site_description',  'Ding Feng 的博客 — 技术、AI、生活'),
  ('default_locale',    'ja'),
  ('deploy_hook_url',   '');  -- Set via CF Pages Deploy Hook; CMS publishes trigger this

-- ============================================================
-- End of 0001_initial.sql
-- ============================================================